- name: Copy files to /etc in chroot
  hosts: chroot_env
  gather_facts: false
  vars:
    - files_to_copy:
        - src: "files/etc/logid.cfg"
          dest: "/etc/logid.cfg"
        - src: "files/etc/nsswitch.conf"
          dest: "/etc/nsswitch.conf"
        - src: "files/etc/pacman.conf"
          dest: "/etc/pacman.conf"
        - src: "files/etc/paru.conf"
          dest: "/etc/paru.conf"
        - src: "files/etc/conf.d/pacman-contrib"
          dest: "/etc/conf.d/pacman-contrib"
        - src: "files/etc/conf.d/wireless-regdom"
          dest: "/etc/conf.d/wireless-regdom"
        - src: "files/etc/firewalld/firewalld.conf"
          dest: "/etc/firewalld/firewalld.conf"
        - src: "files/etc/iwd/main.conf"
          dest: "/etc/iwd/main.conf"
        - src: "files/etc/ly/config.ini"
          dest: "/etc/ly/config.ini"
        - src: "files/etc/makepkg.conf.d/99-parallel.conf"
          dest: "/etc/makepkg.conf.d/99-parallel.conf"
        - src: "files/etc/modprobe.d/wifi.conf"
          dest: "/etc/modprobe.d/wifi.conf"
        - src: "files/etc/pam.d/login"
          dest: "/etc/pam.d/login"
        - src: "files/etc/polkit-1/rules.d/10-udisks2-mount.rules"
          dest: "/etc/polkit-1/rules.d/10-udisks2-mount.rules"
        - src: "files/etc/sysctl.d/99-custom.conf"
          dest: "/etc/sysctl.d/99-custom.conf"
        - src: "files/etc/unbound/unbound.conf"
          dest: "/etc/unbound/unbound.conf"
        - src: "files/etc/firewalld/zones/block.xml"
          dest: "/etc/firewalld/zones/block.xml"
        - src: "files/etc/NetworkManager/conf.d/dns.conf"
          dest: "/etc/NetworkManager/conf.d/dns.conf"

    - name: Ensure destination directories exist
      ansible.builtin.file:
        path: "{{ item.dest | dirname }}"
        state: directory
        owner: root
        group: root
        mode: "0755"
      loop: "{{ patch_list.files_to_copy }}"

    - name: Copy files listed in patch list (actual copy)
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: "{{ item.group | default('root') }}"
        mode: "0644"
        backup: yes
        force: no
      loop: "{{ patch_list.files_to_copy }}"
      register: copy_results

    - name: Display copied files
      ansible.builtin.debug:
        msg: "Copied {{ item.dest }}"
      with_items: "{{ copy_results.results }}"
      when: item.changed
