conf.d/pacman-contrib
conf.d/wireless-regdom
firewalld/firewalld.conf
firewalld/zones/block.xml
iwd/main.conf
logid.cfg
ly/config.ini
ly/save.ini
makepkg.conf.d/99-parallel.conf
mkinitcpio.conf
modprobe.d/wifi.conf
NetworkManager/conf.d/dns.conf
nsswitch.conf
pacman.conf
pam.d/login
paru.conf
polkit-1/rules.d/10-udisks2-mount.rules
sudoers.d/mysudo
